# Generated by Django 6.1.1 on 2026-10-02 16:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-z]+$', 'Code IDs contain only lowercase letters and digits, e.g. 3484x2z2w2a4u4q2r28463o5111.')], verbose_name='JuicyAds code ID')),
                ('visits', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='redirect.link')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
