# Generated by Django 6.1.1 on 2026-10-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='blocked_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['link', 'ip', 'created_at'], name='redirect_cl_link_id_a27ac0_idx'),
        ),
    ]
