# Generated by Django 6.1.1 on 2026-10-03 12:29

from django.db import migrations, models
from django.utils.crypto import salted_hmac


def hash_existing_ips(apps, schema_editor):
    # Same as src.redirect.models.hash_ip; copied so the migration doesn't depend on app code.
    Click = apps.get_model("redirect", "Click")
    for click in Click.objects.exclude(ip=None).only("id", "ip").iterator():
        click.ip_hash = salted_hmac("redirect.click.ip", click.ip, algorithm="sha256").hexdigest()
        click.save(update_fields=["ip_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0002_click_blocked_reason'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='click',
            name='redirect_cl_link_id_a27ac0_idx',
        ),
        migrations.AddField(
            model_name='click',
            name='ip_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.RunPython(hash_existing_ips, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['link', 'ip_hash', 'created_at'], name='redirect_cl_link_id_ee9546_idx'),
        ),
    ]
